CC=gcc
AR=ar
RM=rm
CP=cp
MV=mv
MD=mkdir
LN=ln
PROC=proc

CFLAGS=-m64 -fPIC -g -fstack-protector-all

ARFLAGS=

DYNAMIC_LDFLAGS=
STATIC_LDFLAGS=

TONG_INCLUDE=-I(TONGDIR)/TE/incl
TONG_LDFLAGS=$(DYNAMIC_LDFLAGS) -L(TONGDIR)/TE/obj64 -lteapi64

TUXEDO_INCLUDE=-I$(TUXDIR)/include
TUXEDO_LDFLAGS=$(DYNAMIC_LDFLAGS) -L$(TUXDIR)/lib -lwsc

ORA_INCLUDE=-I$(ORACLE_HOME)/precomp/public
ORA_LDFLAGS=$(DYNAMIC_LDFLAGS) -L$(ORACLE_HOME)/lib -lclntsh

PROC_INCLUDE=include=$(ORACLE_HOME)/precomp/public

PROJECTDIR=/root/Dict
PREFIX=/usr/local

LDFLAGS=-m64
SO_LDFLAGS=-shared
